# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: expensy-backend-secrets
  namespace: expensy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-backend
    kind: ClusterSecretStore
  target:
    name: expensy-backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URI
      remoteRef:
        key: backend-database-uri
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
