# yaml-language-server: $schema=https://www.schemastore.org/any.json
#
# ExternalSecret для получения пароля root для MongoDB из Azure Key Vault.
# Будет автоматически создан Kubernetes Secret 'mongodb-root-password-secret'
# с ключом 'mongodb-root-password'.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-root-password
  namespace: expensy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-root-password-secret
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: mongodb-root-password
