apiVersion: v1
kind: Service
metadata:
  name: expensy-frontend
  namespace: expensy
  labels:
    app: expensy-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: expensy-frontend
  type: ClusterIP
