# yaml-language-server: $schema=https://www.schemastore.org/any.json
#
# Кластерный ресурс ClusterSecretStore, связывающий ESO с Azure Key Vault.
# Позволяет всем namespace'ам запрашивать секреты, ссылаясь на этот стор.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-backend
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      # Используем имя Key Vault (по умолчанию expensy-keyvault)
      vaultUrl: "https://expensy-vault-kv.vault.azure.net"
      tenantId: "c77b59e3-35cf-4fde-986a-90f7c1324ae6"
      authSecretRef:
        clientId:
          name: azure-sp-credentials
          key: client-id
          namespace: external-secrets
        clientSecret:
          name: azure-sp-credentials
          key: client-secret
          namespace: external-secrets
