apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expensy-mongodb
  namespace: argocd
  annotations:
    # sync-wave: "3" — mongodb разворачивается после синхронизации ExternalSecret
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mongodb
      targetRevision: 15.6.2
      helm:
        valueFiles:
          - $values/gitops/expensy/mongodb-values.yaml
    - repoURL: https://github.com/musaxasmammedov7/devOps-final-project-expensy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: expensy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
